export const REGISTER_USER_BEGIN = "REGISTER_USER_BEGIN";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";

export const DISPLAY_ALERT = "SHOW_ALERT";
export const CLEAR_ALERT = "CLEAR_ALERT";

export const LOGIN_USER_BEGIN = "LOGIN_USER_BEGIN";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const LOGOUT_USER = "LOGOUT_USER";

export const UPDATE_USER_BEGIN = "UPDATE_USER_BEGIN";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_ERROR = "UPDATE_USER_ERROR";

export const ADD_COMPLAINT_BEGIN = "ADD_COMPLAINT_BEGIN";
export const ADD_COMPLAINT_SUCCESS = "ADD_COMPLAINT_SUCCESS";
export const ADD_COMPLAINT_ERROR = "ADD_COMPLAINT_ERROR";

export const ADD_APPOINTMENT_BEGIN = "ADD_APPOINTMENT_BEGIN";
export const ADD_APPOINTMENT_SUCCESS = "ADD_APPOINTMENT_SUCCESS";
export const ADD_APPOINTMENT_ERROR = "ADD_APPOINTMENT_ERROR";

export const ADD_ORDER_BEGIN = "ADD_ORDER_BEGIN";
export const ADD_ORDER_SUCCES = "ADD_ORDER_SUCCES";
export const ADD_ORDER_ERROR = "ADD_ORDER_ERROR";

export const ADD_ANIMAL_BEGIN = "CREATE_ANIMAL_BEGIN";
export const ADD_ANIMAL_SUCCESS = "CREATE_ANIMAL_SUCCESS";
export const ADD_ANIMAL_ERROR = "CREATE_ANIMAL_ERROR";

export const GET_COMPSUSER_BEGIN = "GET_COMPSUSER_BEGIN";
export const GET_COMPSUSER_SUCCESS = "GET_COMPSUSER_SUCCESS";

export const GET_COMPSCITY_BEGIN = "GET_COMPSCITY_BEGIN";
export const GET_COMPSCITY_SUCCESS = "GET_COMPSCITY_SUCCESS";

export const GET_COMP_BEGIN = "GET_COMP_BEGIN";
export const GET_COMP_SUCCESS = "GET_COMP_SUCCESS";

export const UPDATE_COMPLAINT_BEGIN = "UPDATE_COMPLAINT_BEGIN";

export const DELETE_COMPLAINT_BEGIN = "DELETE_COMPLAINT_BEGIN";

export const GET_ORDERS_BEGIN = "GET_ORDERS_BEGIN";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";

export const GET_ORDER_BEGIN = "GET_ORDER_BEGIN";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";

export const UPDATE_ORDER_BEGIN = "UPDATE_ORDER_BEGIN";

export const DELETE_ORDER_BEGIN = "DELETE_ORDER_BEGIN";

export const GET_RESAPPS_BEGIN = "GET_RESAPPS_BEGIN";
export const GET_RESAPPS_SUCCESS = "GET_RESAPPS_SUCCESS";

export const DELETE_RESAPP_BEGIN = "DELETE_RESAPP_BEGIN";

export const GET_USERAPPS_BEGIN = "GET_USERAPPS_BEGIN";
export const GET_USERAPPS_SUCCESS = "GET_USERAPPS_SUCCESS";

export const GET_CONTACTS_BEGIN = "GET_CONTACTS_BEGIN";
export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS";

export const DELETE_CONTACT_BEGIN = "DELETE_CONTACT_BEGIN";

export const ADD_FEEDBACK_BEGIN = "ADD_FEEDBACK_BEGIN";
export const ADD_FEEDBACK_SUCCESS = "ADD_FEEDBACK_SUCCESS";
export const ADD_FEEDBACK_ERROR = "ADD_FEEDBACK_ERROR";

export const GET_FEEDBACKS_BEGIN = "GET_FEEDBACKS_BEGIN";
export const GET_FEEDBACKS_SUCCESS = "GET_FEEDBACKS_SUCCESS";

export const DELETE_FEEDBACK_BEGIN = "DELETE_FEEDBACK_BEGIN";
